// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const accountCreate = `-- name: AccountCreate :one
INSERT INTO accounts (name, email, document_type, document_number, sources)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, document_type, document_number, sources, status, created_at, updated_at
`

type AccountCreateParams struct {
	Name           string
	Email          string
	DocumentType   string
	DocumentNumber string
	Sources        []string
}

func (q *Queries) AccountCreate(ctx context.Context, arg AccountCreateParams) (Account, error) {
	row := q.db.QueryRow(ctx, accountCreate,
		arg.Name,
		arg.Email,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.Sources,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Sources,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const accountGet = `-- name: AccountGet :one
SELECT id, name, email, document_type, document_number, sources, status, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) AccountGet(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, accountGet, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Sources,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const accountGetForUpdate = `-- name: AccountGetForUpdate :one
SELECT id, name, email, document_type, document_number, sources, status, created_at, updated_at FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) AccountGetForUpdate(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, accountGetForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Sources,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const accountUpdateStatus = `-- name: AccountUpdateStatus :one
UPDATE accounts SET status = $2, updated_at = now() WHERE id = $1 RETURNING updated_at
`

type AccountUpdateStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) AccountUpdateStatus(ctx context.Context, arg AccountUpdateStatusParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, accountUpdateStatus, arg.ID, arg.Status)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const accountWorkspaceCreate = `-- name: AccountWorkspaceCreate :one
INSERT INTO workspaces (account_id, name, email, document_type, document_number, mcc)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, name, email, document_type, document_number, mcc, status, created_at, updated_at
`

type AccountWorkspaceCreateParams struct {
	AccountID      uuid.UUID
	Name           string
	Email          string
	DocumentType   string
	DocumentNumber string
	Mcc            string
}

func (q *Queries) AccountWorkspaceCreate(ctx context.Context, arg AccountWorkspaceCreateParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, accountWorkspaceCreate,
		arg.AccountID,
		arg.Name,
		arg.Email,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.Mcc,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Email,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Mcc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const accountWorkspaceGet = `-- name: AccountWorkspaceGet :one
SELECT id, account_id, name, email, document_type, document_number, mcc, status, created_at, updated_at FROM workspaces WHERE id = $1 AND account_id = $2
`

type AccountWorkspaceGetParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) AccountWorkspaceGet(ctx context.Context, arg AccountWorkspaceGetParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, accountWorkspaceGet, arg.ID, arg.AccountID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Email,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Mcc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const accountWorkspaceGetForUpdate = `-- name: AccountWorkspaceGetForUpdate :one
SELECT id, account_id, name, email, document_type, document_number, mcc, status, created_at, updated_at FROM workspaces WHERE id = $1 FOR UPDATE
`

func (q *Queries) AccountWorkspaceGetForUpdate(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, accountWorkspaceGetForUpdate, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Email,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.Mcc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const accountWorkspaceList = `-- name: AccountWorkspaceList :many
SELECT id, account_id, name, email, document_type, document_number, mcc, status, created_at, updated_at FROM workspaces
WHERE account_id = $1 AND ($3::uuid IS NULL OR id < $3)
ORDER BY id DESC
LIMIT $2
`

type AccountWorkspaceListParams struct {
	AccountID     uuid.UUID
	Limit         int32
	StartingAfter uuid.NullUUID
}

func (q *Queries) AccountWorkspaceList(ctx context.Context, arg AccountWorkspaceListParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, accountWorkspaceList, arg.AccountID, arg.Limit, arg.StartingAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Email,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.Mcc,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountWorkspaceUpdateStatus = `-- name: AccountWorkspaceUpdateStatus :one
UPDATE workspaces SET status = $2, updated_at = now() WHERE id = $1 RETURNING updated_at
`

type AccountWorkspaceUpdateStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) AccountWorkspaceUpdateStatus(ctx context.Context, arg AccountWorkspaceUpdateStatusParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, accountWorkspaceUpdateStatus, arg.ID, arg.Status)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
