// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_key.sql

package db

import (
	"context"
)

const aPIKeyCreate = `-- name: APIKeyCreate :exec
INSERT INTO api_keys (key_hash, source) VALUES ($1, $2)
`

type APIKeyCreateParams struct {
	KeyHash []byte
	Source  string
}

func (q *Queries) APIKeyCreate(ctx context.Context, arg APIKeyCreateParams) error {
	_, err := q.db.Exec(ctx, aPIKeyCreate, arg.KeyHash, arg.Source)
	return err
}

const aPIKeySource = `-- name: APIKeySource :one
SELECT source FROM api_keys WHERE key_hash = $1
`

func (q *Queries) APIKeySource(ctx context.Context, keyHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, aPIKeySource, keyHash)
	var source string
	err := row.Scan(&source)
	return source, err
}
