// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const billingCheckoutExists = `-- name: BillingCheckoutExists :one
SELECT EXISTS (SELECT 1 FROM checkouts WHERE id = $1 AND workspace_id = $2)
`

type BillingCheckoutExistsParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) BillingCheckoutExists(ctx context.Context, arg BillingCheckoutExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, billingCheckoutExists, arg.ID, arg.WorkspaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const billingGet = `-- name: BillingGet :one
SELECT id, workspace_id, checkout_id, amount, currency, payment_method, installments, status, idempotency_key, captured_at, created_at, updated_at FROM bills WHERE id = $1 AND workspace_id = $2
`

type BillingGetParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) BillingGet(ctx context.Context, arg BillingGetParams) (Bill, error) {
	row := q.db.QueryRow(ctx, billingGet, arg.ID, arg.WorkspaceID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CheckoutID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Installments,
		&i.Status,
		&i.IdempotencyKey,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const billingGetByKey = `-- name: BillingGetByKey :one
SELECT id, workspace_id, checkout_id, amount, currency, payment_method, installments, status, idempotency_key, captured_at, created_at, updated_at FROM bills WHERE workspace_id = $1 AND idempotency_key = $2
`

type BillingGetByKeyParams struct {
	WorkspaceID    uuid.UUID
	IdempotencyKey string
}

func (q *Queries) BillingGetByKey(ctx context.Context, arg BillingGetByKeyParams) (Bill, error) {
	row := q.db.QueryRow(ctx, billingGetByKey, arg.WorkspaceID, arg.IdempotencyKey)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CheckoutID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Installments,
		&i.Status,
		&i.IdempotencyKey,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const billingGetForUpdate = `-- name: BillingGetForUpdate :one
SELECT id, workspace_id, checkout_id, amount, currency, payment_method, installments, status, idempotency_key, captured_at, created_at, updated_at FROM bills WHERE id = $1 FOR UPDATE
`

func (q *Queries) BillingGetForUpdate(ctx context.Context, id uuid.UUID) (Bill, error) {
	row := q.db.QueryRow(ctx, billingGetForUpdate, id)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CheckoutID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Installments,
		&i.Status,
		&i.IdempotencyKey,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const billingInsert = `-- name: BillingInsert :one
INSERT INTO bills (workspace_id, checkout_id, amount, currency, payment_method, installments, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (workspace_id, idempotency_key) DO NOTHING
RETURNING id, workspace_id, checkout_id, amount, currency, payment_method, installments, status, idempotency_key, captured_at, created_at, updated_at
`

type BillingInsertParams struct {
	WorkspaceID    uuid.UUID
	CheckoutID     uuid.NullUUID
	Amount         int64
	Currency       string
	PaymentMethod  string
	Installments   int32
	IdempotencyKey string
}

func (q *Queries) BillingInsert(ctx context.Context, arg BillingInsertParams) (Bill, error) {
	row := q.db.QueryRow(ctx, billingInsert,
		arg.WorkspaceID,
		arg.CheckoutID,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
		arg.Installments,
		arg.IdempotencyKey,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CheckoutID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Installments,
		&i.Status,
		&i.IdempotencyKey,
		&i.CapturedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const billingInsertTransaction = `-- name: BillingInsertTransaction :exec
INSERT INTO transactions (bill_id, amount, status, code, provider, idempotency_key, provider_created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (bill_id, idempotency_key) DO NOTHING
`

type BillingInsertTransactionParams struct {
	BillID            uuid.UUID
	Amount            int64
	Status            string
	Code              string
	Provider          string
	IdempotencyKey    string
	ProviderCreatedAt *time.Time
}

func (q *Queries) BillingInsertTransaction(ctx context.Context, arg BillingInsertTransactionParams) error {
	_, err := q.db.Exec(ctx, billingInsertTransaction,
		arg.BillID,
		arg.Amount,
		arg.Status,
		arg.Code,
		arg.Provider,
		arg.IdempotencyKey,
		arg.ProviderCreatedAt,
	)
	return err
}

const billingListByCheckout = `-- name: BillingListByCheckout :many
SELECT id, workspace_id, checkout_id, amount, currency, payment_method, installments, status, idempotency_key, captured_at, created_at, updated_at FROM bills
WHERE workspace_id = $1 AND checkout_id = $2
  AND ($4::uuid IS NULL OR id < $4)
ORDER BY id DESC
LIMIT $3
`

type BillingListByCheckoutParams struct {
	WorkspaceID   uuid.UUID
	CheckoutID    uuid.NullUUID
	Limit         int32
	StartingAfter uuid.NullUUID
}

func (q *Queries) BillingListByCheckout(ctx context.Context, arg BillingListByCheckoutParams) ([]Bill, error) {
	rows, err := q.db.Query(ctx, billingListByCheckout,
		arg.WorkspaceID,
		arg.CheckoutID,
		arg.Limit,
		arg.StartingAfter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CheckoutID,
			&i.Amount,
			&i.Currency,
			&i.PaymentMethod,
			&i.Installments,
			&i.Status,
			&i.IdempotencyKey,
			&i.CapturedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingTransactions = `-- name: BillingTransactions :many
SELECT id, bill_id, amount, status, code, provider, idempotency_key, provider_created_at, created_at FROM transactions WHERE bill_id = $1 ORDER BY id
`

func (q *Queries) BillingTransactions(ctx context.Context, billID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, billingTransactions, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.Amount,
			&i.Status,
			&i.Code,
			&i.Provider,
			&i.IdempotencyKey,
			&i.ProviderCreatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const billingUpdate = `-- name: BillingUpdate :one
UPDATE bills SET status = $2, captured_at = $3, updated_at = now() WHERE id = $1 RETURNING updated_at
`

type BillingUpdateParams struct {
	ID         uuid.UUID
	Status     string
	CapturedAt *time.Time
}

func (q *Queries) BillingUpdate(ctx context.Context, arg BillingUpdateParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, billingUpdate, arg.ID, arg.Status, arg.CapturedAt)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const billingWorkspace = `-- name: BillingWorkspace :one
SELECT w.id, w.status, coalesce(r.external_id, '')::text AS connected_account
FROM workspaces w
LEFT JOIN provider_refs r ON r.entity_type = 'workspace' AND r.entity_id = w.id AND r.provider = $1
WHERE w.id = $2 AND w.account_id = $3
`

type BillingWorkspaceParams struct {
	Provider  string
	ID        uuid.UUID
	AccountID uuid.UUID
}

type BillingWorkspaceRow struct {
	ID               uuid.UUID
	Status           string
	ConnectedAccount string
}

func (q *Queries) BillingWorkspace(ctx context.Context, arg BillingWorkspaceParams) (BillingWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, billingWorkspace, arg.Provider, arg.ID, arg.AccountID)
	var i BillingWorkspaceRow
	err := row.Scan(&i.ID, &i.Status, &i.ConnectedAccount)
	return i, err
}
