// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const checkoutCountUses = `-- name: CheckoutCountUses :one
SELECT count(*) FROM bills WHERE checkout_id = $1 AND status <> 'error'
`

func (q *Queries) CheckoutCountUses(ctx context.Context, checkoutID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, checkoutCountUses, checkoutID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkoutCreate = `-- name: CheckoutCreate :one
INSERT INTO checkouts (id, workspace_id, name, items, payment_methods, max_uses, expires_at, external_reference, url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, name, items, payment_methods, max_uses, expires_at, external_reference, url, status, created_at, updated_at
`

type CheckoutCreateParams struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	Name              string
	Items             json.RawMessage
	PaymentMethods    []string
	MaxUses           *int32
	ExpiresAt         *time.Time
	ExternalReference *string
	Url               string
}

func (q *Queries) CheckoutCreate(ctx context.Context, arg CheckoutCreateParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, checkoutCreate,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Items,
		arg.PaymentMethods,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.ExternalReference,
		arg.Url,
	)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Items,
		&i.PaymentMethods,
		&i.MaxUses,
		&i.ExpiresAt,
		&i.ExternalReference,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkoutGet = `-- name: CheckoutGet :one
SELECT id, workspace_id, name, items, payment_methods, max_uses, expires_at, external_reference, url, status, created_at, updated_at FROM checkouts WHERE id = $1 AND workspace_id = $2
`

type CheckoutGetParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) CheckoutGet(ctx context.Context, arg CheckoutGetParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, checkoutGet, arg.ID, arg.WorkspaceID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Items,
		&i.PaymentMethods,
		&i.MaxUses,
		&i.ExpiresAt,
		&i.ExternalReference,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkoutGetForUpdate = `-- name: CheckoutGetForUpdate :one
SELECT id, workspace_id, name, items, payment_methods, max_uses, expires_at, external_reference, url, status, created_at, updated_at FROM checkouts WHERE id = $1 AND workspace_id = $2 FOR UPDATE
`

type CheckoutGetForUpdateParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) CheckoutGetForUpdate(ctx context.Context, arg CheckoutGetForUpdateParams) (Checkout, error) {
	row := q.db.QueryRow(ctx, checkoutGetForUpdate, arg.ID, arg.WorkspaceID)
	var i Checkout
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Items,
		&i.PaymentMethods,
		&i.MaxUses,
		&i.ExpiresAt,
		&i.ExternalReference,
		&i.Url,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkoutList = `-- name: CheckoutList :many
SELECT id, workspace_id, name, items, payment_methods, max_uses, expires_at, external_reference, url, status, created_at, updated_at FROM checkouts
WHERE workspace_id = $1 AND ($3::uuid IS NULL OR id < $3)
ORDER BY id DESC
LIMIT $2
`

type CheckoutListParams struct {
	WorkspaceID   uuid.UUID
	Limit         int32
	StartingAfter uuid.NullUUID
}

func (q *Queries) CheckoutList(ctx context.Context, arg CheckoutListParams) ([]Checkout, error) {
	rows, err := q.db.Query(ctx, checkoutList, arg.WorkspaceID, arg.Limit, arg.StartingAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Checkout
	for rows.Next() {
		var i Checkout
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Items,
			&i.PaymentMethods,
			&i.MaxUses,
			&i.ExpiresAt,
			&i.ExternalReference,
			&i.Url,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkoutUpdateStatus = `-- name: CheckoutUpdateStatus :one
UPDATE checkouts SET status = $2, updated_at = now() WHERE id = $1 RETURNING updated_at
`

type CheckoutUpdateStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) CheckoutUpdateStatus(ctx context.Context, arg CheckoutUpdateStatusParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, checkoutUpdateStatus, arg.ID, arg.Status)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const checkoutWorkspace = `-- name: CheckoutWorkspace :one
SELECT w.id, w.status, coalesce(r.external_id, '')::text AS connected_account
FROM workspaces w
LEFT JOIN provider_refs r ON r.entity_type = 'workspace' AND r.entity_id = w.id AND r.provider = $1
WHERE w.id = $2 AND w.account_id = $3
`

type CheckoutWorkspaceParams struct {
	Provider  string
	ID        uuid.UUID
	AccountID uuid.UUID
}

type CheckoutWorkspaceRow struct {
	ID               uuid.UUID
	Status           string
	ConnectedAccount string
}

func (q *Queries) CheckoutWorkspace(ctx context.Context, arg CheckoutWorkspaceParams) (CheckoutWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, checkoutWorkspace, arg.Provider, arg.ID, arg.AccountID)
	var i CheckoutWorkspaceRow
	err := row.Scan(&i.ID, &i.Status, &i.ConnectedAccount)
	return i, err
}
