// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID             uuid.UUID
	Name           string
	Email          string
	DocumentType   string
	DocumentNumber string
	Sources        []string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Bill struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	CheckoutID     uuid.NullUUID
	Amount         int64
	Currency       string
	PaymentMethod  string
	Installments   int32
	Status         string
	IdempotencyKey string
	CapturedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Checkout struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	Name              string
	Items             json.RawMessage
	PaymentMethods    []string
	MaxUses           *int32
	ExpiresAt         *time.Time
	ExternalReference *string
	Url               string
	Status            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProviderRef struct {
	EntityType string
	EntityID   uuid.UUID
	Provider   string
	ExternalID string
	Data       json.RawMessage
	CreatedAt  time.Time
}

type Transaction struct {
	ID                uuid.UUID
	BillID            uuid.UUID
	Amount            int64
	Status            string
	Code              string
	Provider          string
	IdempotencyKey    string
	ProviderCreatedAt *time.Time
	CreatedAt         time.Time
}

type WebhookEvent struct {
	ID             int64
	Provider       string
	IdempotencyKey string
	EventType      string
	Payload        json.RawMessage
	ProcessedAt    *time.Time
	CreatedAt      time.Time
}

type Workspace struct {
	ID             uuid.UUID
	AccountID      uuid.UUID
	Name           string
	Email          string
	DocumentType   string
	DocumentNumber string
	Mcc            string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
