// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shared.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const providerRefExists = `-- name: ProviderRefExists :one
SELECT EXISTS (SELECT 1 FROM provider_refs WHERE entity_type = $1 AND entity_id = $2 AND provider = $3)
`

type ProviderRefExistsParams struct {
	EntityType string
	EntityID   uuid.UUID
	Provider   string
}

func (q *Queries) ProviderRefExists(ctx context.Context, arg ProviderRefExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, providerRefExists, arg.EntityType, arg.EntityID, arg.Provider)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const providerRefFind = `-- name: ProviderRefFind :one
SELECT entity_type, entity_id, provider, external_id, data, created_at FROM provider_refs WHERE provider = $1 AND external_id = $2
`

type ProviderRefFindParams struct {
	Provider   string
	ExternalID string
}

func (q *Queries) ProviderRefFind(ctx context.Context, arg ProviderRefFindParams) (ProviderRef, error) {
	row := q.db.QueryRow(ctx, providerRefFind, arg.Provider, arg.ExternalID)
	var i ProviderRef
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.Provider,
		&i.ExternalID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const providerRefUpsert = `-- name: ProviderRefUpsert :exec
INSERT INTO provider_refs (entity_type, entity_id, provider, external_id, data)
VALUES ($1, $2, $3, $4, '{}')
ON CONFLICT (entity_type, entity_id, provider) DO UPDATE SET external_id = excluded.external_id
`

type ProviderRefUpsertParams struct {
	EntityType string
	EntityID   uuid.UUID
	Provider   string
	ExternalID string
}

func (q *Queries) ProviderRefUpsert(ctx context.Context, arg ProviderRefUpsertParams) error {
	_, err := q.db.Exec(ctx, providerRefUpsert,
		arg.EntityType,
		arg.EntityID,
		arg.Provider,
		arg.ExternalID,
	)
	return err
}

const webhookInsert = `-- name: WebhookInsert :one
INSERT INTO webhook_events (provider, idempotency_key, event_type, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider, idempotency_key) DO NOTHING
RETURNING id
`

type WebhookInsertParams struct {
	Provider       string
	IdempotencyKey string
	EventType      string
	Payload        json.RawMessage
}

func (q *Queries) WebhookInsert(ctx context.Context, arg WebhookInsertParams) (int64, error) {
	row := q.db.QueryRow(ctx, webhookInsert,
		arg.Provider,
		arg.IdempotencyKey,
		arg.EventType,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const webhookMarkProcessed = `-- name: WebhookMarkProcessed :exec
UPDATE webhook_events SET processed_at = now() WHERE id = $1
`

func (q *Queries) WebhookMarkProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, webhookMarkProcessed, id)
	return err
}
